import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Separator } from "@/components/ui/separator"
import localFont from "next/font/local";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"

export const metadata = {
  title: "Admin Caserio",
  description: "Generated by create next app",
};

const neikoFont = localFont({
  src: "../assets/fonts/NeikoRegular-XGMP2.woff",
    variable: "--font-neiko",
    display: "swap",
});

const satoshiFont = localFont({
    src: [
        { path: "../assets/fonts/Satoshi-Light.otf", weight: "300", style: "normal" },
        { path: "../assets/fonts/Satoshi-Regular.otf", weight: "400", style: "normal" },
        { path: "../assets/fonts/Satoshi-Medium.otf", weight: "500", style: "normal" },
        { path: "../assets/fonts/Satoshi-Bold.otf", weight: "700", style: "normal" },
    ],
    variable: "--font-satoshi",
    display: "swap",
});

export default function RootLayout({ children }) {
    return (
    <html lang="es" className={`${satoshiFont.variable} ${neikoFont.variable}`}>
      <body className={`${satoshiFont.variable} ${neikoFont.variable} font-sans`}>
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 border-b px-4 bg-[#131415]">
              <SidebarTrigger className="-ml-1" />
              <Separator orientation="vertical" className="mr-2 h-4 bg-[#F6F6F6]" />   
              
                <Breadcrumb>
                  <BreadcrumbList>
                    <BreadcrumbItem className="hidden md:block">
                      <BreadcrumbLink href="#">
                        Propiedades
                      </BreadcrumbLink>
                    </BreadcrumbItem>
                    <BreadcrumbSeparator className="hidden md:block" />
                    <BreadcrumbItem>
                      <BreadcrumbPage>Casa Lomas de Angelópolis</BreadcrumbPage>
                    </BreadcrumbItem>
                  </BreadcrumbList>
                </Breadcrumb>
            </header>
            <main className="flex-1 p-4 bg-[#131415]">
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
