# Generated by Django 6.0 on 2025-12-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='area',
            new_name='construction',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='terrain',
            field=models.CharField(default=350, max_length=50),
            preserve_default=False,
        ),
    ]
