# Generated by Django 6.0 on 2025-12-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_area_propiedad_construction_propiedad_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
