# Generated by Django 6.0 on 2025-12-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_propiedad_available_propiedad_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='images',
        ),
    ]
